#!/bin/sh
set -e

# Deploy to Firebase Hosting at https://mandelbrot-595fd.web.app/
if [ "$CIRCLECI" = "true" ]; then
  firebase deploy --token "$FIREBASE_TOKEN" --non-interactive
else
  firebase deploy
fi
