#!/bin/sh
set -e

# Install development dependencies
if [ "$CIRCLECI" != "true" ]; then
  cargo install --force watchexec
fi

# Install Rust dependencies
rustup target add wasm32-unknown-unknown
cargo install --force wasm-pack

# Install web frontend dependencies
cd mandelbrot-web/
npm install
cd ../

# Setup location for installing global npm packages
if [ "$CIRCLECI" = "true" ]; then
  npm config set prefix=/home/circleci/npm
  echo 'export PATH="/home/circleci/npm/bin:$PATH"' >>$BASH_ENV
fi

# Install development and deployment tools
npm install -g firebase-tools
